#!/usr/bin/env python
from time import time
import numpy as np
import random
import heapq

def kesimo(a,k):
    heapq.heapify(a)
    for i in range(0,k):
        if i == k:
            return heapq.heappop(a)
        else:
            x=heapq.heappop(a)
    return x
def listaAleatorios(n):
    lista = []
    for i in range(1,n):
         lista.append(i)

    random.shuffle(lista)
    return lista

a = listaAleatorios(6400000)
tiempo_inicial = time()
print kesimo(a,40)
tiempo_final = time()

tiempo_ejecucion = tiempo_final - tiempo_inicial

print 'El tiempo de ejecucion fue:',tiempo_ejecucion
