#!/usr/bin/env python

from time import time
import random
import heapq

def listaAleatorios(n):
    lista = []
    for i in range(1,n):
         lista.append(i)
    random.shuffle(lista)
    return lista
def topM(a,k):
  b = []
  heapq.heapify(a)
  for i in range(0,k):
    b.append(heapq.heappop(a))
  return b


a = listaAleatorios(100000)
tiempo_inicial = time()
print topM(a,10)
tiempo_final = time()

tiempo_ejecucion = tiempo_final - tiempo_inicial
print 'El tiempo de ejecucion fue:',tiempo_ejecucion
